### ISSUE TITLE
`verify` doesn't fail the test

### ISSUE THREAD

**Issue by doobnet** [MetalheadSanya/swift-mock#55]
I noticed that `verify` doesn't fail the test when the call count doesn't match. I eventually figured out that there's a global closure variable, `testFailureReport`,  that `verify` calls to report a test failure. But the `testFailureReport` closure by default doesn't do anything. What's the reason for this? I also haven't found this mentioned in the documentation, that one needs to set `testFailureReport` to something useful.

**Comment by MetalheadSanya** [comment]
Hi, thanks for the question. The target with the library is linked to the target being developed because mocks are currently being generated in it. Therefore, it is impossible to link the XCTest library to it.

I will cover this point in the documentation and in the future I plan to make a separate target that can be connected to a target with tests, which will have a function that allows you to configure the engine to work.

**Comment by MetalheadSanya** [comment]
#56

**Comment by doobnet** [comment]
I see. How about using a plain Swift `assert` in the default implementation of `testFailureReport` that says it should be replaced with `XCTFail` or something similar? That will make it extra visible if someone has not read the documentation.

**Comment by MetalheadSanya** [comment]
Nice idea, thank you very much.

**Comment by MetalheadSanya** [comment]
Expecting changes:
1. Change default implementation of `testFailureReport` to assertion.

That should help user setup engine correctly.
That should prevert user from fake success tests without correct setup the engine.
